id: I6AF2224B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-14T12:16:40+00:00'
last_modified: '2022-06-10T04:54:27.659380+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29106
  title: ཕྱི་རྒྱུད་ཀྱི་འགྲེལ་པ་མུན་སེལ་སྒྲོན་མེ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    5AD4:
      image_group_id: I1PD388
      title: Volume 1 of phyi rgyud kyi 'grel pa mun sel sgron me
      total_pages: 240
      order: 1
      base_file: 5AD4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
